version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api/app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: on-failure
